import 'package:esooul/Widgets/header.dart';
import 'package:flutter/material.dart';

import '../IELTS Home/ielts_widget.dart';

class Grammer extends StatefulWidget {
  const Grammer({Key? key}) : super(key: key);

  @override
  _GrammerState createState() => _GrammerState();
}

class _GrammerState extends State<Grammer> {
String bullet="\u2022";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Container(
          child: Column(
        children: [
          Header(btntext: 'IELTS grammer'),
          Container(
            // height: MediaQuery.of(context).size.height *.27,

            padding: EdgeInsets.symmetric(horizontal: 20, vertical: 20),
            child: Column(
              children: [
                // grammerAndVocabularyCard(context, 'assets/png/listeningGrammer.png',"IELTS Listening Grammer"),
                // grammerAndVocabularyCard(context,'assets/png/writingGrammer.png', 'IELTS Writing Grammer'),
                // grammerAndVocabularyCard(context,'assets/png/readingGrammer.png', 'IELTS Reading Grammer'),
                // grammerAndVocabularyCard(context,'assets/png/speakingGrammer.png', 'IELTS Speaking Grammer'),

                Container(
                    // color: Colors.amber,
                    width: double.infinity,
                    height: MediaQuery.of(context).size.height * .67,
                    child: SingleChildScrollView(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          SizedBox(
                            height: MediaQuery.of(context).size.height * .02,
                          ),
                          Text(
                            "IELTS test sections Listening Preparation help",
                            style: TextStyle(color: Color(0xff196C7E)),
                          ),
                          SizedBox(
                            height: MediaQuery.of(context).size.height * .02,
                          ),
                          myHeading(context, 'Grammar'),
                          myHeading(context, 'Articles:'),
                          myText(context,
                              'In English there are three articles: a, an, and the. Articles are used before nouns or noun equivalents and are a type of adjective. The definite article (the) is used before a noun to indicate that the identity of the noun is known to the reader. The indefinite article (a, an) is used before a noun that is general or when its identity is not known. There are certain situations in which a noun takes no article.'),
                          myText(context,
                              'As a guide, the following definitions and table summarize the basic use of articles. Continue reading for a more detailed explanation of the rules and for examples of how and when to apply them.'),
                          myHeading(context, 'Definite article'),
                          myHeading(context, ''),
                          myText(context,
                              'the (before a singular or plural noun)'),
                          myHeading(context, 'Indefinite article'),
                          myText(context,
                              'a (before a singular noun beginning with a consonant sound)'),
                          myText(context,
                              'an (before a singular noun beginning with a vowel sound)'),
                          myText(context,
                              'Count nouns - refers to items that can be counted and are either singular or plural'),
                          myText(context,
                              'Non-count nouns - refers to items that are not counted and are always singular'),
                          snapshot(context, "assets/png/grammer1.png"),
                          myText(context,
                              'For the purposes of understanding how articles are used, it is important to know that nouns can be either count (can be counted) or noncount (indefinite in quantity and cannot be counted). In addition, count nouns are either singular (one) or plural (more than one). Noncount nouns are always in singular form.'),
                          myText(context,
                              'For example, if we are speaking of water that has been spilled on the table, there can be one drop (singular) or two or more drops (plural) of water on the table. The word drop in this example is a count noun because we can count the number of drops. Therefore, according to the rules applying to count nouns, the word drop would use the articles a or the.'),
                          myText(context,
                              'However, if we are speaking of water in general spilled on the table, it would not be appropriate to count one water or two waters -- there would simply be water on the table. '),
                          myText(context,
                              'However, if we are speaking of water in general spilled on the table, it would not be appropriate to count one water or two waters -- there would simply be water on the table. Water is a noncount noun. Therefore, according to the rules applying to noncount nouns, the word water would use no article or the, but not a.'),
                          myText(context,
                              'Following are the three specific rules which explain the use of definite and indefinite articles.'),
                          myHeading(context,
                              'Rule #1 - Specific identity not known: Use the indefinite article a or an only with a singular count noun whose specific identity is not known to the reader. Use a before nouns that begin with a consonant sound, and use an before nouns that begin with a vowel sound.'),
                          bulletCard(context,
                              'Use the article a or an to indicate any non-specified member of a group or category.'),
                          myText(context, 'I think an animal is in the garage'),
                          myText(context, 'That man is a scoundrel.'),
                          myText(context, 'We are looking for an apartment.'),
                          bulletCard(context,
                              'Use the article a or an to indicate one in number (as opposed to more than one).'),
                          myText(context, 'I own a cat and two dogs.'),
                          bulletCard(context,
                              'Use the article a before a consonant sound, and use an before a vowel sound.'),
                          myText(context, 'a boy, an apple'),
                          myText(context,
                              '◊ Sometimes an adjective comes between the article and noun:'),
                          myText(context, 'an unhappy boy, a red apple'),
                          bulletCard(context,
                              'The plural form of a or an is some. Use some to indicate an unspecified, limited amount (but more than one).'),
                          myText(context, 'an apple, some apples'),
                          myHeading(context,
                              'Rule #2 - Specific identity known: Use the definite article the with any noun (whether singular or plural, count or noncount) when the specific identity of the noun is known to the reader, as in the following situations:'),
                          bulletCard(context,
                              'Use the article the when a particular noun has already been mentioned previously.'),
                          myText(context,
                              'I ate an apple yesterday. The apple was juicy and delicious.'),
                          bulletCard(context,
                              'Use the article the when an adjective, phrase, or clause describing the noun clarifies or restricts its identity.'),
                          myText(context,
                              'The boy sitting next to me raised his hand.'),
                          myText(
                              context, 'Thank you for the advice you gave me.'),
                          bulletCard(context,
                              'Use the article the when the noun refers to something or someone that is unique.'),
                          myText(context, 'the theory of relativity'),
                          myText(context, 'the 2003 federal budget'),
                          myHeading(context,
                              'Rule #3 - All things or things in general: Use no article with plural count nouns or any noncount nouns used to mean all or in general.'),
                          myText(context,
                              'Trees are beautiful in the fall. (All trees are beautiful in the fall.)'),
                          myText(context,
                              'He was asking for advice. (He was asking for advice in general.)'),
                          myText(context,
                              'I do not like coffee. (I do not like all coffee in general.)'),
                          myHeading(context,
                              'Additional Information Regarding the Use of Articles'),
                          bulletCard(context,
                              'When indicating an unspecified, limited amount of a count or noncount noun, use some. My cousin was seeking some advice from a counselor (not advice in general or advice about everything, but a limited amount ofadvice).'),
                          myText(context,
                              'I would love some coffee right now (not coffee in general, but a limited amount of coffee).'),
                          myText(context,
                              'We might get rain tomorrow. Some rain would be good for the crops (a certain amount of rain, as opposed to rain in general).'),
                          myText(context,
                              'There are some drops of water on the table (a limited number, but more than one drop).'),
                          bulletCard(context,
                              'Noncount nouns are those which usually cannot be counted. Following are some common examples:'),
                          myText(context,
                              '◊ Certain food and drink items: bacon, beef, bread, broccoli, butter, cabbage, candy, cauliflower, celery, cereal, cheese, chicken, chocolate, coffee, corn, cream, fish, flour, fruit, ice cream, lettuce, meat, milk, oil, pasta, rice, salt, spinach, sugar, tea, water, wine, yogurt'),
                          myText(context,
                              '◊ Certain nonfood substances: air, cement, coal, dirt, gasoline, gold, paper, petroleum, plastic, rain, silver, snow, soap, steel, wood, wool'),
                          myText(context,
                              '◊ Most abstract nouns: advice, anger, beauty, confidence, courage, employment, fun, happiness, health, honesty, information, intelligence, knowledge, love, poverty, satisfaction, truth, wealth'),
                          myText(context,
                              '◊ Areas of study: history, math, biology, etc.'),
                          myText(context,
                              '◊ Sports: soccer, football, baseball, hockey, etc.'),
                          myText(context,
                              '◊ Languages: Chinese, Spanish, Russian, English, etc.'),
                          myText(context,
                              '◊ Other: clothing, equipment, furniture, homework, jewelry, luggage, lumber, machinery, mail, money, news, poetry, pollution, research, scenery, traffic, transportation, violence, weather, work'),
                          myHeading(context,
                              'Geographical names are confusing because some require the and some do not.'),
                          myText(context,
                              '◊ Use the with: united countries, large regions, deserts, peninsulas, oceans, seas, gulfs, canals, rivers, mountain ranges, groups of islands'),
                          myText(context, 'the Gobi Desert '),
                          myText(context, 'the United Arab Emirates '),
                          myText(context, 'the Sacramento River the Aleutians'),
                          myText(context,
                              '◊ Do not use the with: streets, parks, cities, states, counties, most countries, continents, bays, single lakes, single mountains, islands'),
                          myText(context, 'Japan'),
                          myText(context, 'Chico'),
                          myText(context, 'Mt. Everest'),
                          myText(context, 'San Francisco Bay'),
                          myHeading(context, 'Examples of the Use of Articles'),
                          myText(context,
                              'I do not want a gun in my house (any gun).'),
                          myText(context,
                              'The gun is in his closet (implies there is a specific gun).'),
                          myText(context,
                              'I am afraid of guns (all guns in general).'),
                          myText(context,
                              'She sent me a postcard from Italy (an unspecific postcard - not a letter, not an e-mail).'),
                          myText(context,
                              'Its the postcard that I have in my office (one specific postcard).'),
                          myText(context,
                              'Getting postcards makes me want to travel (any postcard in general).'),
                          myText(context, 'I have a dog (one dog).'),
                          myText(context,
                              'The dog is very friendly (the dog that I have already mentioned).'),
                          myText(context,
                              'Dogs make great pets (dogs in general).'),
                          myText(context,
                              'Greta needs furniture in her apartment (furniture is a noncount noun). She is going to select the furniture that she needs (the specific furniture that she needs). She hopes to find some furniture this weekend (an unspecified limited amount of furniture).'),
                          myText(context,
                              'We are going to see the Statue of Liberty this weekend (the only Statue of Liberty).'),
                          myHeading(context, 'Comparisons'),
                          myHeading(context,
                              'Comparative and Superlative Adjectives'),
                          myText(context,
                              'Being able to compare and contrast data is an essential skill for IELTS writing, especially in '),
                          myText(context,
                              'Task 1.  Comparatives and superlatives are one common way to do this.'),
                          myText(context,
                              'Comparatives are used to compare two things:'),
                          myText(context, 'Leopards are faster than tigers.'),
                          myText(context,
                              'Superlatives are used to compare one thing against a group of others:'),
                          myText(context,
                              'The leopard is the largest of the four big cats.'),
                          myText(context,
                              'Here are the basics of how they are formed:'),
                          snapshot(context, "assets/png/grammer2.png"),
                          myHeading(context, 'Other Important Language'),
                          myText(context,
                              'Comparatives and superlatives are useful to compare and contrast, but they wont be enough.'),
                          myText(context,
                              'Here are some other useful words and structures:'),
                          myHeading(context, 'Transitions'),
                          bulletCard(context,
                              'The Middle East produces high levels of oil; however, Japan produces none.'),
                          bulletCard(context,
                              'The USA produces large amounts of natural gas.  In contrast, South Korea produces none.'),
                          bulletCard(context,
                              'European countries make great use of solar power.  On the other hand, most Asian countries us this method of power generation very little.'),
                          myHeading(context, 'Subordinating Conjunctions'),
                          bulletCard(context,
                              'The Middle East produces high levels of oil, whereas / while Japan produces none.'),
                          bulletCard(context,
                              'Whereas / While the Middle East produces high levels of oil, Japan produces none.'),
                          bulletCard(context,
                              'Although the Middle East produced 100 tons oil, Japan produced none.'),
                          myHeading(context, 'Other Structures'),
                          bulletCard(context,
                              'Developing countries are more reliant on alternative energy production than developed countries.'),
                          bulletCard(context,
                              'Solar power accounts for far less of the total energy production than gas or coal does.'),
                          bulletCard(context,
                              'Hydropower is not as efficient as wind power.'),
                          bulletCard(context,
                              'Like Japan, South Korea does not produce any natural gas.'),
                          bulletCard(context,
                              'The Middle East produces twice as much oil as Europe.'),
                          bulletCard(context,
                              'Western countries consume three times more oil than the Middle East.'),
                          bulletCard(context,
                              'Russia consumes slightly more oil than Germany.'),
                          bulletCard(context,
                              'The UAE produced the same amount of oil as Saudi Arabia.'),
                          myHeading(context, 'Using Approximate Data'),
                          myText(context,
                              'When you compare and contrast, you also need to learn phrases so you can refer to data that is not exact.'),
                          myText(context, 'For example:'),
                          snapshot(context, "assets/png/grammer3.PNG"),
                          myHeading(context,
                              'Compare and Contrast Language Practice'),
                          myText(context,
                              'Look at the table below.  What is being compared?'),
                          myText(context,
                              'Natural Gas Consumption and Production, 2001'),
                          snapshot(context, "assets/png/grammer4.png"),
                          myHeading(context, '- Conjunctions'),
                          myText(context, 'Conjunctions are parts of speech that connect words, phrases, clauses, or sentences. There are three kinds of conjunctions: coordinating, paired, and subordinating.'),
                          myText(context, 'For more information about conjunctions, also see these webpages:'),
                          bulletCard(context,'Compound Sentences,'),
                          bulletCard(context,'Varying Sentence Structure, and'),
                          bulletCard(context,'Comma Basics.'),
                          myText(context, 'Coordinating conjunctions connect words or phrases that serve the same grammatical purpose in a sentence. There are seven main coordinating conjunctions in English, which form the acronym FANBOYS:'),
                          myText(context, 'F: for: The teachers were frustrated, for the school had cut funding for all enrichment programs.*'),
                          myText(context, 'A: and: In this course, I will write a literature review, a case study, and a final paper.**'),
                          myText(context, 'N: nor: The students did not complete their homework, nor did they pass the test.'),
                          myText(context, 'B: but: The study is several years old but still valuable to this study.'),
                          myText(context, 'O: or: At the end of the class, the students can choose to write an essay or take a test.'),
                          myText(context, 'Y: yet: The patient complained of chronic pain, yet she refused treatment.'),
                          myText(context, 'S: so: I have only been a nurse for one year, so I have little experience with paper charting.'),
                          myText(context, '* "For" is rarely used as a conjunction in modern English.'),
                          myText(context, '** When the conjunctions "and" and "or" connect three or more words or phrases, use a serial comma to separate items in the series. '),
                          myText(context, 'Transitional words such as "however" and "therefore" can also function as conjunctions:'),
                          bulletCard(context, 'The authors agreed on the prevalence of the problem; however, they disagreed on the problem’s cause.'),
                          bulletCard(context, 'Several employees complained about the new policies, and therefore, the manager held an all-staff meeting to address their concerns.'),
                          myText(context, 'Paired conjunctions consist of two words or phrases that help make a point or establish alternatives. Although paired conjunctions can be helpful in structuring a sentence, they can also make sentences wordier than necessary, so use these conjunctions sparingly.'),
                          myText(context, 'both…and'),
                          bulletCard(context, 'The project will require significant investments of both time and money.'),
                          bulletCard(context, 'Both the students and the teachers were satisfied with the pilot program.'),
                          myText(context,'Note: When two subjects are connected by "both…and," use a plural verb (such as "are" or "were").'),

                          myText(context, 'not only…but also'),
                          bulletCard(context, 'Students who did not complete the assignment received not only a poor grade but also a warning from the teacher.'),
                          bulletCard(context, 'Not only did the student include full sentences from the source without using quotation marks, but he also failed to properly cite paraphrased material.'),

                          myText(context, 'either…or'),
                          bulletCard(context, 'Either the students were unprepared or the assessment was poorly written.'),
                          bulletCard(context, 'Participants in the survey could either choose from a list of possible answers or write in their own responses.'),

                          myText(context, 'neither…nor'),
                          bulletCard(context, 'Students who did not complete the project received neither praise nor rewards.'),
                          bulletCard(context, 'The staff neither followed the new policy nor asked for clarification.'),

                          myText(context, 'Subordinating conjunctions join a subordinate clause to a main clause and establishes a relationship between the two. There are many subordinating clauses, but here are some of the most common:'),
                          bulletCard(context,'after'),
                          bulletCard(context,'although'),
                          bulletCard(context,'as much as/as soon as/as long as'),
                          bulletCard(context,'as though'),
                          bulletCard(context,'because'),
                          bulletCard(context,'before'),
                          bulletCard(context,'how'),
                          bulletCard(context,'if'),
                          bulletCard(context,'in order to/in order that'),
                          bulletCard(context,'once'),
                          bulletCard(context,'since'),
                          bulletCard(context,'than'),
                          bulletCard(context,'that'),
                          bulletCard(context,'though'),
                          bulletCard(context,'unless'),
                          bulletCard(context,'until'),
                          bulletCard(context,'when/whenever'),
                          bulletCard(context,'where/wherever'),
                          bulletCard(context,'whether'),
                          bulletCard(context,'while'),
                          myText(context, 'There are two ways to structure a sentence using a subordinating conjunction:'),
                          myHeading(context,'Main clause + subordinate clause'),
                          bulletCard(context,'The teacher administered the test after giving instructions.'),
                          bulletCard(context,'The author must avoid bias if she wants to maintain a scholarly tone.'),
                          bulletCard(context,'I will turn in this assignment at midnight whether or not I complete it.'),
                          myHeading(context, 'Subordinate clause + , + main clause'),
                          bulletCard(context,'After giving instructions, the teacher administered the test.'),
                          bulletCard(context,'If she wants to maintain a scholarly tone, the author must avoid bias.'),
                          bulletCard(context,'Whether or not I complete this assignment, I will turn it in at midnight.'),

                          myText(context, '"That" has a few different functions in English. This can lead to confusion because some instances of "that" are more optional than others in academic writing.'),
                          myText(context, 'One important use of "that" is for embedding (inserting) a certain type of dependent clause called a noun clause into an independent clause. Frequently, such "that" clauses serve as the direct object of a reporting verb (such as found, reported, posited, argued, claimed, maintained, and hypothesized) to introduce a paraphrase, summary, or quotation.'),
                          Row(
      children: [
        Wrap(
          children: [
            Text(
              'Key:',
              style: TextStyle(color: Colors.black, fontSize: 10),
            ),
             Text(
              'Yellow, bold',
              style: TextStyle(color: Colors.black, fontSize: 10,backgroundColor: Colors.yellow),
            ), Text(
              ' = subject;',
              style: TextStyle(color: Colors.black, fontSize: 10),
            ), Text(
              'green, underline ',
              style: TextStyle(color: Colors.black, fontSize: 10,backgroundColor: Colors.green),
            ), Text(
              ' = verb;',
              style: TextStyle(color: Colors.black, fontSize: 10),
            ), Text(
              'blue, italics ',
              style: TextStyle(color: Colors.black, fontSize: 10,backgroundColor: Colors.cyan),
            ), Text(
              '= object',
              style: TextStyle(color: Colors.black, fontSize: 10),
            ),
          ],
        ),
        
      ],
    ), 
    
    
                          myText(context, 'For example,'),
    
    Row(
      children: [
        Wrap(
          children: [
            Text('$bullet   ',style: TextStyle(color: Colors.black),),
            
             Text(
              'Smith (2015)',
              style: TextStyle(color: Colors.black, fontSize: 10,backgroundColor: Colors.yellow),
            )
            , Text(
              ' reported',
              style: TextStyle(color: Colors.black, fontSize: 10,backgroundColor: Colors.green),
            ), Text(
              'that more research was necessary.',
              style: TextStyle(color: Colors.black, fontSize: 10,backgroundColor: Colors.cyan),
            ),
          ],
        ),
        
      ],
    ),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                          myText(context, ''),
                        ],
                      ),
                    ))
              ],
            ),
          )
        ],
      )),
    );
  }
}
