import 'package:esooul/Screens/Ielts%20Section/IELTS%20Home/ielts_widget.dart';
import 'package:esooul/Widgets/header.dart';
import 'package:flutter/material.dart';


class AboutSpeaking extends StatefulWidget {
  const AboutSpeaking({ Key? key }) : super(key: key);

  @override
  _AboutSpeakingState createState() => _AboutSpeakingState();
}

class _AboutSpeakingState extends State<AboutSpeaking> {
  @override
  Widget build(BuildContext context) {
     return Scaffold(
      backgroundColor: Colors.white,
      body: Container(
        child: Column(
          // crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Header(btntext: 'About Speaking Test'),
            SizedBox(
              height: MediaQuery.of(context).size.height * .01,
            ),
            // Row(
            //   mainAxisAlignment: MainAxisAlignment.start,
            //   children: [
            //     Padding(
            //       padding: const EdgeInsets.only(left:25),
            //       child: Text("About Listening test",style: TextStyle(color: Colors.black),),
            //     ),
            //   ],
            // ),
            // SizedBox(
            //   height: MediaQuery.of(context).size.height * .03,
            // ),
            Container(
              // color: Colors.amber,
              height: MediaQuery.of(context).size.height * .67,
              padding: EdgeInsets.symmetric( horizontal: 20),
              child: SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [

                     SizedBox(
                      height: MediaQuery.of(context).size.height * .02,
                    ),
                    myHeading(context, 'Test format'),
                    myText(context, 'You will talk to a certified examiner in the IELTS Speaking test. The test is interactive and as close to a real-life situation as a test can get. A variety of accents may be used, and the test will be recorded.'),
                    myText(context, 'The content of the IELTS Speaking test is the same for both the IELTS Academic and IELTS General Training tests.'),
                    myText(context, 'The IELTS Speaking test is designed to assess a wide range of skills.'),
                    myText(context, 'The examiner will want to see how well you can'),
                    bulletCard(context, '	communicate opinions and information on everyday topics and common experiences; to do this you will need to answer a range of questions'),
                    bulletCard(context, '	speak at length on a given topic using appropriate language'),
                    bulletCard(context, '	organise your ideas coherently'),
                    bulletCard(context, '	express and justify your opinions'),
                    bulletCard(context, '	analyse, discuss and speculate about issues'),
                    myText(context, 'Make sure that you relax and talk fluently. You will need to speak naturally.'),
                    snapshot(context, 'assets/png/speaking1.PNG'),
                    myHeading(context, 'Assessment Criteria'),
                    myText(context, 'IELTS Speaking scores are calculated using 4 criteria:'),
                    myHeading(context, '1.	Fluency and coherence (FC) = how clear and structured is your speech.'),
                    myText(context, 'To increase score for FC:'),
                    myText(context, '1.	connect your sentences by linking words and signpoints'),
                    myText(context, '2.	extend your answers, add all the relevant details'),
                    myText(context, '3.	speak smoothly and continuously'),
                    myText(context, '4.	use pausing correctly'),
                    myHeading(context, '2.	Lexical Resource (LR) = how good is your vocabulary.'),
                    myText(context, 'To increase score for LR:'),
                    myText(context, '1.	use a wide range of vocabulary'),
                    myText(context, '2.	discuss different topics freely, using appropriate words'),
                    myText(context, '3.	speak formally or semi-formally'),
                    myText(context, '4.	choose words accurately'),
                    myText(context, '5.	use idiomatic language'),
                    myHeading(context, '3.	Pronunciation (P) = how naturally you sound.'),
                    myText(context, 'To increase score for P:'),
                    myText(context, '1.	pronounce words as clearly as possible'),
                    myText(context, '2.	record your speech and work on the words that you spell incorrectly'),
                    myText(context, '3.	stress words and sentences correctly'),
                    myText(context, '4.	use correct intonations'),
                    myText(context, '5.	try to be easily understood by the examiner.'),
                    myText(context, '4.	Grammatical Range and Accuracy (GRA) = how good is your grammar.'),
                    myText(context, ''),
                    myText(context, 'To increase score for GRA:'),
                    myText(context, '1.	avoid grammatical mistakes'),
                    myText(context, '2.	try to use more advanced grammatical structures (passive voice, direct speech, different tenses and conditional sentences etc)'),
                    myText(context, ''),

                    myHeading(context, 'IELTS Speaking score calculation'),
                    myText(context, 'Each of these criteria receives a score from 0 to 9 points. After that, an arithmetic mean is calculated to determine the section\'s total score. For example, if your marks are: FC - 7, P - 8, LR - 7 and GR - 6, your total score will be (7+8+7+6)/4 = 7'),
                    myText(context, 'For example, if your marks are:'),
                    bulletCard(context, '	Fluency and Cohesion: 7.5,'),
                    bulletCard(context, '	Pronunciation: 7.0,'),
                    bulletCard(context, '	Lexical Resource: 7.0,'),
                    bulletCard(context, '	Grammatical Range and Accuracy - 7.5.'),
                    myText(context, ''),
                    myText(context, 'Then your total score for IELTS Speaking is (7.5+7.0+7.0+7.5)/4 =7.25, which will be rounded to 7.5.'),
                    myText(context, ''),
                    myHeading(context, 'Checklist:'),
                    myText(context, 'I speak fluently with no pauses or hesitation'),
                    myText(context, 'I speak accurately '),
                    myText(context, 'I speak clearly'),
                    myText(context, 'I manage my time efficiently'),
                    myText(context, 'I organize my self well as I speak'),
                    myText(context, 'I use wide rage of grammar and vocabulary'),
                    myText(context, 'I can use complex sentences and a range of functions'),
                    myText(context, 'I can develop an argument'),
                    myText(context, 'I use appropriate linking words'),
                    myText(context, 'I use the correct word and sentences stress and sentence rythem'),
                    myHeading(context, 'Take a Quiz'),
                    myText(context, 'There are different Speaking tests for General and Academic IELTS.'),
                    myText(context, 'False( Answer ) There speaking test is the same for general training and academic IELTS '),
                    myText(context, 'True '),
                    myText(context, 'How long will the Speaking test take?'),
                    myText(context, '5-10'),
                    myText(context, '11-14  ( Answer ) Each IELTS speaking interview takes between 11-14 minutes to complete'),
                    myText(context, '15-20'),
                    myText(context, 'How many parts does the Speaking test Consist of ?'),
                    myText(context, '3 ( Answer ) The speaking test consists of three different parts'),
                    myText(context, '1'),
                    myText(context, '5'),
                    myText(context, 'When answering the examiner’s questions, it is not acceptable to say only “yes” or “no”.'),
                    myText(context, 'True ( Answer ) You must use full sentences to show the examiner that you can communicate you ideas in English'),
                    myText(context, 'False'),
                    myText(context, 'Which part of the Speaking test requires fairly brief responses ?'),
                    myText(context, 'Part 1 ( Answer ) You must answer in full sentences  and briefly give reasons for your answer.'),
                    myText(context, 'Part 2'),
                    myText(context, 'Part 3'),
                    myText(context, 'Test takers are allowed to refuse to speak about a certain topic if they don’t know much about it.'),
                    myText(context, 'True'),
                    myText(context, 'False ( Answer ) It is not important how much you know about a topic, but how well you express yourself in English.'),
                    myText(context, 'Which part of the Speaking test requires a lengthy two minutes response ?'),
                    myText(context, 'Part 1'),
                    myText(context, 'Part 2 ( Answer ) There examiner will expect you to speak for 2 minutes about the topic you are given.'),
                    myText(context, 'Part 3'),
                    myText(context, 'Test takers may request more preparation time for part 2 topic if they don’t feel ready to speak after 1 minute.'),
                    myText(context, 'True'),
                    myText(context, 'False ( Answer ) Examiners don’t give test takers more than one minute. This is to ensure fairness and equality.'),
                    myText(context, 'Which part of the Speaking test requires test takers to compare different ideas and to explain their opinions?'),
                    myText(context, 'Part 1'),
                    myText(context, 'Part 2'),
                    myText(context, 'Part 3 ( Answer ) It tests the ability to use English in a more complex way, voicing your opinions and justifying them.'),
                    myText(context, 'Will test takers get a low score if they express negative opinions or if they don’t agree with the views suggested by the examiner ?'),
                    myText(context, 'Always'),
                    myText(context, 'Sometimes'),
                    myText(context, 'Never ( Answer ) The only thing that is important is how well you use English to express your ideas.'),
                    myText(context, 'Tip 1: Don\'t memorise answers'),
                    myText(context, 'Don\'t memorise answers, especially in Part 1. Memorised language doesn\'t give the examiner an accurate measure of your English-language skills. The examiner will be able to tell if you have memorised your answers and this may influence your final band score.'),
                    myText(context, 'Tip 2: Don\'t use big and unfamiliar words'),
                    myText(context, 'You may want to impress the examiner with big and complex words in your Speaking test. But to be safe, avoid using words you are not familiar with. There is a higher chance of making mistakes by either mispronouncing words or using them in the wrong context. Mistakes can affect your final band score.'),
                    myText(context, 'Use a range of vocabulary that you know which is relevant to the topic being discussed. Look at the topics in Tip 10, making vocabulary lists or mind maps to help you learn more words and phrases connected to these topic areas.'),
                    myText(context, 'Tip 3: Use a range of grammatical structures'),
                    myText(context, 'When IELTS examiners assess your speaking skills, they mark you against the following assessment criteria:'),
                    myText(context, 'Fluency and coherence'),
                    myText(context, 'Lexical resource'),
                    myText(context, 'Grammatical range and accuracy'),
                    myText(context, 'Pronunciation'),
                    myText(context, 'Try and use a range of grammatical structures using complex and simple sentences to express what you want to say. Know your own errors and practice speaking to friends in English, or record yourself to see if you can spot errors. If you hear an error, make sure to correct yourself. You are assessed on your ability to use different grammatical structures accurately, so it\'s important to practise speaking about the past, the present and the future using correct tenses.'),
                    myText(context, 'Tip 4: Don\'t worry about your accent'),
                    myText(context, 'With a face-to-face Speaking test, the IELTS examiner understands a wide range of accents so will be able to understand what you say, unlike an AI machine. If you can communicate well, then there is nothing to worry about. But do be aware of sounds that you have difficulty with and make sure to use stress and intonation as English is a stress-timed language. Practice with friends and they will tell you if they can\'t understand what you are saying.'),
                    myText(context, 'Tip 5: Pause to think'),
                    myText(context, 'There is no harm in taking a brief pause to think about what to say. We all do it to process questions. You can use phrases to give you time to think during the Speaking test - phrases such as:'),
                    myText(context, 'That\'s an interesting question'),
                    myText(context, 'I have never thought about that, but...'),
                    myText(context, 'Let me see'),
                    myText(context, 'That\'s a good point'),
                    myText(context, 'That\'s a difficult question, but I\'ll try and answer it'),
                    myText(context, 'Well, some people say that is the case, however I think...'),
                    myText(context, 'Let me think about that for a minute'),
                    myText(context, 'Tip 6: Avoid using fillers'),
                    myText(context, 'Speak confidently and avoid using filler words. We generally use fillers when we don\'t know what to say, however, this shows the examiner that you can\'t access the appropriate language or ideas so it\'s important to avoid them and to use the phrases we gave you in Tip 5.'),
                    myText(context, 'Avoid the following fillers:'),
                    myText(context, 'Like'),
                    myText(context, 'You know'),
                    myText(context, 'Umm...'),
                    myText(context, 'Ahh...'),
                    myText(context, 'Ehh...'),
                    myText(context, 'Well'),
                    myText(context, 'Yeah...'),
                    myText(context, 'Tip 7: Extend your answers'),
                    myText(context, 'Try and answer the examiner\'s questions in full. Extend your answers and don\'t wait for the examiner to prompt you with a question. When your answers are short, this shows the examiner that you cannot talk in detail about a topic. If the examiner says \'Why?\', they are prompting you to give a reason for your answer and to extend more fully.'),
                    myText(context, 'Tip 8: Smiling helps pronunciation'),
                    myText(context, 'Smiling can help calm your nerves which in turn helps your pronunciation. Make sure to enunciate clearly, opening your mouth wide enough so that sounds come out clearly. When we smile, our mouth is bigger and the tone of our voice is more friendly. Using clear enunciation and tone will show the examiner that you can use a range of pronunciation features.'),
                    myText(context, 'Tip 9: Don\'t speak in a monotone'),
                    myText(context, 'Sometimes when we speak, we produce a flat sound, a monotone, with little variation. This makes it more difficult to express what you say and makes it more difficult for the listener to identify what parts of your message are important. Putting emphasis on certain words and pausing at sections in your speech can make your conversation with the IELTS examiner more engaging. When we emphasise certain words it makes it easier to compare and contrast ideas by stressing key words. It also increases the flow of conversation, so remember:'),
                    myText(context, 'Don\'t speak in a monotone'),
                    myText(context, 'Vary the stress and intonation to add emphasis'),
                    myText(context, 'Use your hands to gesture and help the rhythm of the conversation'),
                    myText(context, 'Tip 10 - Practice common IELTS topics'),
                    myText(context, 'Part 2 of the IELTS Speaking test requires you to speak on a given topic for about 2 minutes. Practice common IELTS topics with friends, family or colleagues to improve and to learn vocabulary associated with each topic.'),
                    myText(context, 'Common topics you can practice for the Speaking test include:'),
                    myText(context, 'Tourism and travel'),
                    myText(context, 'Education'),
                    myText(context, 'Transport'),
                    myText(context, 'Environment'),
                    myText(context, 'Family life'),
                    myText(context, 'Sport and recreation'),
                    myText(context, 'Crime and punishment'),
                    myText(context, 'The internet'),
                    myText(context, 'Advertising and retail'),
                    myText(context, ''),
                    myHeading(context, 'Test Tips'),
                    myText(context, ''),
                    myText(context, 'The best way to become better at speaking English is to practise speaking English regularly . This is great news - it means you can prepare for IELTS exam by chatting with people! ( Who said exam preparation had to be boring?)'),
                    myText(context, 'If you talk regularly with a teacher or a native speaker, ask them to correct your mistakes.'),
                    myText(context, 'However, fluency is more important too, so when you’re chatting with other non-native speakers, don’t worry too much that you might be making mistakes. Make sure you’re speaking fluently and getting your message across. You can still get a high score in the exam if your grammar isn’t perfect'),
                    myText(context, 'Try to avoid basic grammar mistakes though. A lot if candidates lose marks by confusing ‘he’ and ‘she’, or never using the past tense. This can confuse the listener, and will limit tge IELTS score you can receive.'),
                    myText(context, ''),
                    

                  ],
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}