import 'dart:io';

const BaseUrl = "http://www.esooul.com";

const IeltsBaseUrl = "http://ielts.esooul.com";

// final headers = {
//   HttpHeaders.contentTypeHeader: 'application/json; charset=UTF-8',
//   HttpHeaders.acceptHeader: 'application/json',
//   // 'Authorization':
//   //     'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMTA5ZTFkNTIxYTI3N2Q5MzZjNzdmZjkzNmU3ZjBlOWMwNjU4NjVlNzAyMWQyOTY5NTc3MDVhMTBmZjM3ZjZhMjMwN2ZlOTM2NTE3MTMzMmYiLCJpYXQiOjE2MzIwMzEzNjEsIm5iZiI6MTYzMjAzMTM2MSwiZXhwIjoxNjYzNTY3MzYxLCJzdWIiOiI2NyIsInNjb3BlcyI6W119.Eke0LszkPF0o7u33PQDyRDdKfqMMi-k4l5pp63vIKJEAmm7WKgIT3uSaVagTcNaJC2igLa1CRXxfS9uofIH86tendq-xCaLH5JPZGhbQ_zqKltBPEOV9jDZvMMicra1sVvnDly5Ob6ANNznp8FF__BTS8bma_q4uPUODDvLJoMgxzzEMBgz1SEYT_1HQ0DcXY5Ny5v1_bRruKdAKkoiyqaZn-2mDKeAI6ZZIvTlyzJi2hLsZMbVLYQ8ntAqRp_4bG-A2xmT2nyfnZ7yyTYAQ5lYOe7SNhNa67YCgmGaLdkqxFRxkGMRA6O3-aAQAF_xgYwfKz93oP-TboRgfUfid3pn5DQsyyaZajm5OU1R_ebmp5ifgx7hgR1vcbMKptUM9vBiK1hilGaTJT0NQpaO6-YRBJtADLXdMuWbxLJP1grlnsnjvMoOyNFnBx7DkqW_SXudAQcmb-dSy2SYUs6Pq-QjFAPJK0WoG4ypqnJrGhpL8lUErIF7Kq-pHedcpAN5t5PQNj8vfo9dneaIB8evSGYokgECptORN6JOf_9HEDB9GC8zyxBY5w9Z9bzeRpiYRb6uHYGFiFnAeU4hkcg-a0e0YS4rGpfc8W6EHjlFhNdQbsvdOJp4IxPJKsrD32MhqcIqRgj2bfIlGQeurFxg0wf7ujbbfNF_XlMAR5Bg7gtA'
// };
